# **Pandas**

In [167]:
import pandas as pd

## Series

In [168]:
# Create a Series from list
val = [1, 2, 3]
obj = pd.Series(val)

# Creating Series with string index
ind = ['a', 'b', 'c']
obj2 = pd.Series(val, index=ind)

# Creating Series from dictionary
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}
obj3 = pd.Series(sdata)

# Access and modify
obj['0'] = 5
obj2['a'] # 1
obj['0']  # 5

# Selecting multiple values
obj[[1, 2]]

# index order
states = ['California', 'Ohio', 'Oregon', 'Texas']
obj4 = pd.Series(sdata, index=states)

# Detecting missing data
pd.isnull(obj4)    # True for NaN value
pd.notnull(obj4)   # False for NaN value
obj4.isnull()      # instance method

obj4.name = 'population'      # Series name
obj4.index.name = 'state'     # index name

print(f'obj:\n{obj}')
print(f'\nobj2:\n{obj2}')
print(f'\nobj3:\n{obj3}')
print(f'\nobj4:\n{obj4}')

obj:
0    1
1    2
2    3
0    5
dtype: int64

obj2:
a    1
b    2
c    3
dtype: int64

obj3:
Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

obj4:
state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

## DataFrame

In [169]:
# Create dataframe from dictionary

data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
        'year': [2000, 2001, 2002, 2001, 2002, 2003],
        'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}
df = pd.DataFrame(data)

# add and order columns
df1 = pd.DataFrame(data, columns=['year', 'state', 'pop', 'debt'],
                   index=['one', 'two', 'three', 'four', 'five', 'six'])

print(f'{df}\n{df1}')

    state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2
       year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [170]:
df.head()  # only the first 5 rows
df.columns # Index(['state', 'year', 'pop'], dtype='object')
df.values

array([['Ohio', 2000, 1.5],
       ['Ohio', 2001, 1.7],
       ['Ohio', 2002, 3.6],
       ['Nevada', 2001, 2.4],
       ['Nevada', 2002, 2.9],
       ['Nevada', 2003, 3.2]], dtype=object)

### Indexing, Selection, and Filtering

In [171]:
import numpy as np


# Accessing Data
df['state']
df.state
df[1:]

df[df['pop'] > 1]
df[['state', 'year']]      # df[['col1', 'col2']]
df1.loc[['three', 'four']] # df.loc[['idx1', 'idx2']]

# Modifying DataFrames
val = pd.Series([-1.2, -1.5, -1.7], index=['two', 'four', 'five'])
df1['debt'] = val
# only the debt col changes in index 2, 4, 5
# other: NaN

df1['eastern'] = df1.state == 'Ohio'
df1

       year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7  -1.2     True
three  2002    Ohio  3.6   NaN     True
four   2001  Nevada  2.4  -1.5    False
five   2002  Nevada  2.9  -1.7    False
six    2003  Nevada  3.2   NaN    False

In [172]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
    index=['Ohio', 'Colorado', 'Utah', 'New York'],
    columns=['one', 'two', 'three', 'four'])
data[data < 5] = 0
data
# data > 4

          one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

### Selection with loc and iloc

In [173]:
# loc & iloc

data.loc['Colorado', ['two', 'three']]
data.iloc[2, [3, 0, 1]] # third row, 4, 1, 2 column
data.iloc[2] # Utah column
data.iloc[[1, 2], [3, 0, 1]] # row:[1, 2] col:[3, 0, 1] 
data.loc[:'Utah', 'two'] # 1 to 3 row, col tow
data.iloc[:, :3][data.three > 5]

          one  two  three
Colorado    0    5      6
Utah        8    9     10
New York   12   13     14

|Method |	Purpose |	Syntax Example	| Notes|
|-------|-----------|-------------------|------|
`df[val]`	|Select column(s) or filter rows|	`df['col'] or df[['col1','col2']]`	|Also accepts boolean arrays (filter rows), slices (slice rows), or boolean DataFrames
`df.loc[val]`|	Select rows by label	|`df.loc['row_label']`|	Label-based row selection
`df.loc[:, val]`	|Select columns by label|	`df.loc[:, 'col']`|	Label-based column selection
`df.loc[val1, val2]`|	Select rows & columns by label	|`df.loc['row', 'col']`	|Label-based 2D selection
`df.iloc[where]`|	Select rows by integer position	|`df.iloc[0]	`|Integer position-based row selection
`df.iloc[:, where]`|	Select columns by integer position	|`df.iloc[:, 0]`	|Integer position-based column selection
`df.iloc[where_i, where_j]`	|Select rows & columns by integer position|	`df.iloc[0, 1]`|	Integer position-based 2D selection
`df.at[label_i, label_j]`	| Get/set single value by label	| `df.at['row', 'col'] = 5	`| Fast scalar access by label
`df.iat[i, j]`|	Get/set single value by position|	`df.iat[0, 1] = 5`|	Fast scalar access by integer position
`reindex()`	| Select rows/columns by labels| 	`df.reindex(new_labels)`	|Align data with new index
`get_value()`/`set_value()`	|Get/set single value by label	|` df.get_value('row','col')`	|Legacy method (use `.at `instead)

In [174]:
pop = {'Nevada': {2001: 2.4, 2002: 2.9},
        'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}

df3 = pd.DataFrame(pop)
df3.T # swap rows and columns

pd.DataFrame(pop, index=[2001, 2002, 2003])

pdata = {'Ohio': df3['Ohio'][:-1],
    'Nevada': df3['Nevada'][:2]}
pd.DataFrame(pdata)

      Ohio  Nevada
2001   1.7     2.4
2002   3.6     2.9

In [175]:
# Filtering
df[df['pop'] > 2]
df.query('pop > 2')

# Sorting
df.sort_values('year')
df.sort_index()

    state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

## Pandas DataFrame Cheat Sheet

### **Creating DataFrames**
| Method | Example | Description |
|--------|---------|-------------|
| From dict of lists | `pd.DataFrame({'col1': [1,2], 'col2': [3,4]})` | Most common method |
| From dict of dicts | `pd.DataFrame({'A': {0:1, 1:2}, 'B': {0:3, 1:4}})` | Outer keys = columns, inner keys = index |
| From list of dicts | `pd.DataFrame([{'a':1, 'b':2}, {'a':3, 'b':4}])` | Each dict = row |
| From 2D array | `pd.DataFrame(np.array([[1,2],[3,4]]))` | With optional index/columns |

### **Accessing Data**
| Operation | Syntax | Returns |
|-----------|--------|---------|
| Single column | `df['col']` or `df.col` | Series |
| Single row | `df.loc['index']` | Series |
| Multiple columns | `df[['col1', 'col2']]` | DataFrame |
| Multiple rows | `df.loc[['idx1', 'idx2']]` | DataFrame |

### **Modifying DataFrames**
| Operation | Method |
|-----------|--------|
| Add column (Length must match)| `df['new_col'] = values` |  
| Delete column | `del df['col']` or `df.drop('col', axis=1)` |
| Rename columns | `df.rename(columns={'old':'new'})` | 
| Set index | `df.set_index('col')` | 
| Reset index | `df.reset_index()` |

### **Useful Attributes/Methods**
| Attribute/Method | Description |
|------------------|-------------|
| `df.head(n)` | First n rows |
| `df.tail(n)` | Last n rows |
| `df.shape` | (rows, columns) |
| `df.columns` | Column names |
| `df.index` | Index values |
| `df.dtypes` | Data types per column |
| `df.values` | Underlying numpy array |
| `df.T` | Transpose |
| `df.describe()` | Summary statistics |

#### Important Notes
1. **Column access**: `df['col']` works for all names, `df.col` only for valid Python identifiers
2. **Views vs copies**: Column access returns a view (modifications affect original)
3. **Alignment**: Operations align on index
4. **Missing data**: Represented as NaN
5. **Display**: In Jupyter, shows as HTML table

### Index Objects

In [176]:
idx1 = pd.Index([1, 2, 3, 4])
idx2 = pd.Index([3, 4, 5, 6])

# Find elements in idx1 but not in idx2
idx1.difference(idx2)

Index([1, 2], dtype='int64')

In [177]:
# Find common elements between two Index objects
idx1.intersection(idx2)

Index([3, 4], dtype='int64')

In [178]:
# Combine all unique elements from two Index objects
idx1.union(idx2)

Index([1, 2, 3, 4, 5, 6], dtype='int64')

In [179]:
# Concatenate two Index objects
idx1.append(idx2)

Index([1, 2, 3, 4, 3, 4, 5, 6], dtype='int64')

In [180]:
# Check which elements exist in another collection
idx1.isin(idx2)

array([False, False,  True,  True])

In [181]:
# Delete element at specific position
idx1.delete(2)

Index([1, 2, 4], dtype='int64')

In [182]:
# Remove specific values from Index
idx2.drop([3, 4])

Index([5, 6], dtype='int64')

In [183]:
# Insert element at specific position
idx2.insert(0, 3)

Index([3, 3, 4, 5, 6], dtype='int64')

In [184]:
# Check if Index is monotonically increasing
print(idx1.is_monotonic_increasing)
print(idx1.is_monotonic_decreasing)

True
False

In [185]:
# Check if Index has duplicate values
print(idx1.is_unique)

True

In [186]:
# Get unique values from Index
idx = pd.Index([1, 2, 2, 3, 3, 3, 4])
idx.unique()

Index([1, 2, 3, 4], dtype='int64')

In [187]:
# Reindex with new order and add new index 'e'
obj = pd.Series([4.5, 7.2, -5.3, 3.6], index=['d', 'b', 'a', 'c'])
obj.reindex(['a', 'b', 'c', 'd', 'e'])
# e    NaN  (new index with NaN value)

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [188]:
frame = pd.DataFrame(np.arange(9).reshape((3, 3)),
                     index=['a', 'c', 'd'],
                     columns=['Ohio', 'Texas', 'California'])
frame.reindex(['a', 'b', 'c', 'd'])
# Result: Adds row 'b' with NaN values

   Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [189]:
# Reindex rows
frame2 = frame.reindex(['a', 'b', 'c', 'd'])
# Result: Adds row 'b' with NaN values

# Reindex with forward fill (ffill)
obj3 = pd.Series(['blue', 'purple', 'yellow'], index=[0, 2, 4])
obj3_filled = obj3.reindex(range(6), method='ffill')
obj3_filled

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [190]:
# Select specific rows and columns using loc
states = ['Texas', 'Utah', 'California']
# selected = frame.loc[['a', 'b', 'c', 'd'], states]  # KeyError

# This will raise a KeyError because 'b' does not exist in the index
# loc does NOT automatically create NaN for missing indexes/columns
# Uncommenting the line below will cause an error:
# selected = frame.loc[rows, states]  # KeyError: "['b'] not in index"

In [191]:
# Reindex with custom fill value
obj_reindexed = obj.reindex(['a', 'b', 'c', 'd', 'e'], fill_value=0)
# Missing values will be filled with 0 instead of NaN

In [192]:
# Reindex with forward fill and limit
obj3_limited = obj3.reindex(range(6), method='ffill', limit=1)
# Only fills one position forward, others remain NaN

In [193]:
# Reindex columns
frame_reindexed_cols = frame.reindex(columns=['California', 'Texas', 'Ohio', 'Nevada'])
# Reorders columns and adds new column 'Nevada' with NaN values

In [194]:
# Reindex columns
frame_reindexed_cols = frame.reindex(columns=['California', 'Texas', 'Ohio', 'Nevada'])
# Reorders columns and adds new column 'Nevada' with NaN values

In [195]:
# Reindex both rows and columns
frame_reindexed = frame.reindex(index=['a', 'b', 'c', 'd'], 
                                columns=['Texas', 'Utah', 'California'])

Method	| Syntax |	Description |	Example|
--------|--------|--------------|----------|
reindex() - Series|	`series.reindex(new_index)`|	Reorder/expand Series with new index|	`pd.Series([1,2,3], index=['a','b','c']).reindex(['c','a','b','d'])`	|
reindex() - DataFrame|	`df.reindex(index=new_idx, columns=new_cols)`|	Reorder/expand DataFrame rows and columns	|`df.reindex(index=['a','b'], columns=['col1','col2'])`	|
reindex() - with method	| `series.reindex(new_idx, method="ffill")`|	Reindex with forward/backward filling|	`pd.Series(['A','B'], index=[0,2]).reindex(range(4), method='ffill')`	|

### Dropping Entries from an Axis

In [196]:
# drop
obj = pd.Series(np.arange(5.), index=['a', 'b', 'c', 'd', 'e'])
print(obj.drop(['a', 'b']))

new_obj = obj.drop('a')
print(new_obj)

obj.drop('a', inplace=True)
# or
# obj = obj.drop('a')
print(obj)

c    2.0
d    3.0
e    4.0
dtype: float64
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [197]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
        index=['Ohio', 'Colorado', 'Utah', 'New York'],
        columns=['one', 'two', 'three', 'four'])

data = data.drop(['Colorado', 'Ohio']) # delete row
data = data.drop(['two', 'four'], axis='columns') # or axis=1
data

          one  three
Utah        8     10
New York   12     14

### Arithmetic and data alignment

In [198]:
s1 = pd.Series([7.3, -2.5, 3.4, 1.5], index=['a', 'c', 'd', 'e'])
s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1], index=['a', 'c', 'e', 'f', 'g'])

print(s1.add(s2)) 
# value with same lable are added
# produces NaN for non-overlapping indices

print(s1.add(s2, fill_value=0))  
# Addition with fill_value (fills missing values before operation)
# s1: f=0, e=0 s2:d=0

s1 + 10 # adds 10 to all element

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64
a    5.2
c    1.1
d    3.4
e    0.0
f    4.0
g    3.1
dtype: float64

a    17.3
c     7.5
d    13.4
e    11.5
dtype: float64

In [199]:
df1 = pd.DataFrame(np.arange(12.).reshape((3, 4)), columns=list('abcd'))
df2 = pd.DataFrame(np.arange(20.).reshape((4, 5)), columns=list('abcde'))
df2.loc[1, 'b'] = np.nan
df1.add(df2, fill_value=0)

      a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0   5.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

|Method|	Operator| Equivalent|	Purpose	Example|
|------|------------|-----------|------------------|
`add()` / `radd()`	|+|	Addition	|`df.add(other)` or` df + other`
`sub()` / `rsub()`	|-|	Subtraction|	`df.sub(other)` or `df - other`
`div()` / `rdiv()`|	/|	Division|	`df.div(other)` or `df / other`
`floordiv()` / `rfloordiv()`	|//	| Floor division|	`df.floordiv(other)` or` df // other`
`mul() / rmul()`|	*|	Multiplication	|`df.mul(other)` or `df * other`
`pow() / rpow()`|	**|	Exponentiation	|`df.pow(2)` or `df ** 2`

    Note: r prefix methods handle reverse operations (e.g., radd() for other + df)

### Function Application and Mapping

In [200]:
# apply
df = pd.DataFrame(np.random.randint(-10, 10, size=(4, 3)), columns=list('abc'),
                  index=['Utah', 'Ohio', 'Texas', 'Oregon'])

format = lambda x: '%.2f' % x

print(df.map(format))
df['a'].map(format)

            a      b      c
Utah    -3.00   9.00  -2.00
Ohio     1.00  -7.00  -2.00
Texas   -8.00   6.00   2.00
Oregon   9.00  -8.00  -4.00

Utah      -3.00
Ohio       1.00
Texas     -8.00
Oregon     9.00
Name: a, dtype: object

In [201]:
f = lambda x: x.max() - x.min()

print(df.apply(f))
df.apply(f, axis='columns')

a    17
b    17
c     6
dtype: int64

Utah      12
Ohio       8
Texas     14
Oregon    17
dtype: int64

In [202]:
# apply on Series
s_numeric = pd.Series([1, 4, 9, 16, 25])

# Using with additional parameters
def power(x, exponent=2):
    return x ** exponent

s_numeric.apply(power, exponent=3)

0        1
1       64
2      729
3     4096
4    15625
dtype: int64

In [203]:
# apply on DataFrame
df = pd.DataFrame({
    'A': [1, 2, 3, 4],
    'B': [10, 20, 30, 40],
    'C': [100, 200, 300, 400]
}, index=['row1', 'row2', 'row3', 'row4'])

print(df)

# Example 1: Applying on columns (axis=0 or axis='index') - default
column_sums = df.apply(np.sum)
print(column_sums)

      A   B    C
row1  1  10  100
row2  2  20  200
row3  3  30  300
row4  4  40  400
A      10
B     100
C    1000
dtype: int64

In [204]:
# Example 2: Applying on rows (axis=1 or axis='columns')
row_sums = df.apply(np.sum, axis=1)
print(row_sums)

row1    111
row2    222
row3    333
row4    444
dtype: int64

In [205]:
# Example 3: Applying custom function on each column
def column_stats(column):
    return pd.Series({
        'mean': column.mean(),
        'std': column.std(),
        'min': column.min(),
        'max': column.max()
    })

stats_df = df.apply(column_stats)
print(stats_df)

             A          B           C
mean  2.500000  25.000000  250.000000
std   1.290994  12.909944  129.099445
min   1.000000  10.000000  100.000000
max   4.000000  40.000000  400.000000

In [206]:
# Example 4: Applying function that returns multiple values
def normalize_and_round(col):
    normalized = (col - col.min()) / (col.max() - col.min())
    return normalized.round(2)

normalized_df = df.apply(normalize_and_round)
print(normalized_df)

         A     B     C
row1  0.00  0.00  0.00
row2  0.33  0.33  0.33
row3  0.67  0.67  0.67
row4  1.00  1.00  1.00

In [207]:
# Example 5: Applying on rows with access to column names
def row_calculation(row):
    return row['A'] * 2 + row['B'] / 10 - row['C'] * 0.01

row_results = df.apply(row_calculation, axis=1)
print(row_results)

row1    2.0
row2    4.0
row3    6.0
row4    8.0
dtype: float64

In [208]:
# Creating sample DataFrame
df_numbers = pd.DataFrame({
    'X': [1.234, 2.567, 3.891],
    'Y': [4.123, 5.456, 6.789],
    'Z': [7.012, 8.345, 9.678]
})

print(df_numbers)

# Example 1: Applying function on each element
rounded_df = df_numbers.map(lambda x: round(x, 1))
print(rounded_df)

       X      Y      Z
0  1.234  4.123  7.012
1  2.567  5.456  8.345
2  3.891  6.789  9.678
     X    Y    Z
0  1.2  4.1  7.0
1  2.6  5.5  8.3
2  3.9  6.8  9.7

In [209]:
# Example 2: Converting data types
df_strings = pd.DataFrame({
    'A': ['1', '2', '3'],
    'B': ['4.5', '5.6', '6.7'],
    'C': ['7', '8', '9']
})

converted_df = df_strings.map(lambda x: float(x) if '.' in x else int(x))
print("\nDataFrame:")
print(converted_df)
print(converted_df.dtypes)

DataFrame:
   A    B  C
0  1  4.5  7
1  2  5.6  8
2  3  6.7  9
A      int64
B    float64
C      int64
dtype: object

In [210]:
# Example 3: Applying conditional function on each element
def format_number(x):
    if x > 5:
        return f"**{x:.2f}**"
    else:
        return f"{x:.2f}"

formatted_df = df_numbers.map(format_number)
print("\nDataFrame :")
print(formatted_df)

DataFrame :
      X         Y         Z
0  1.23      4.12  **7.01**
1  2.57  **5.46**  **8.35**
2  3.89  **6.79**  **9.68**