In [2]:
import pandas as pd
import numpy as np

## Sorting and Ranking

In [3]:
data = {
    'Name': ['Ali', 'Sara', 'Reza', 'Zahra'],
    'Score': [85, 92, 78, 90]
}

df = pd.DataFrame(data)
df.sort_values(by='Score', ascending=False)
# defult:ascending , ascending=Falce : descending

df.sort_values(by=['Name', 'Score'])
# frist sort by name then sort by score

df = pd.DataFrame({
    'Name': ['Ali', 'Sara', 'Reza'],
    'Score': [85, 92, 78]
}, index=['c', 'a', 'b'])

sorted_df = df.sort_index()
# sort by index

df['Rank'] = df['Score'].rank()
# ranks from one through the number of valid data points in an array

df['Rank_Dense'] = df['Score'].rank(method='dense', ascending=False)
# 
df.rank(method='first')
df.rank(ascending=False, method='max')
df

   Name  Score  Rank  Rank_Dense
c   Ali     85   2.0         2.0
a  Sara     92   3.0         1.0
b  Reza     78   1.0         3.0

In [4]:
# Example data
data = {'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve'],
        'Score': [85, 92, 78, 92, 88],
        'Age': [25, 30, 22, 30, 28]}
df = pd.DataFrame(data)

# 1. Using rank()
df['Rank_avg'] = df['Score'].rank(method='average', ascending=False)
df['Rank_dense'] = df['Score'].rank(method='dense', ascending=False)

# 2. Using sort_values()
df_sorted = df.sort_values(by=['Score', 'Age'], ascending=[False, True])

# 3. Using sort_index()
df_reset = df.reset_index()
df_sorted_idx = df_reset.sort_index(ascending=False)

print("Ranking:")
print(df[['Name', 'Score', 'Rank_avg', 'Rank_dense']])

print("\nSorted by Score then Age:")
print(df_sorted)

print("\nSorted by index (descending):")
print(df_sorted_idx)

Ranking:
      Name  Score  Rank_avg  Rank_dense
0    Alice     85       4.0         3.0
1      Bob     92       1.5         1.0
2  Charlie     78       5.0         4.0
3    David     92       1.5         1.0
4      Eve     88       3.0         2.0

Sorted by Score then Age:
      Name  Score  Age  Rank_avg  Rank_dense
1      Bob     92   30       1.5         1.0
3    David     92   30       1.5         1.0
4      Eve     88   28       3.0         2.0
0    Alice     85   25       4.0         3.0
2  Charlie     78   22       5.0         4.0

Sorted by index (descending):
   index     Name  Score  Age  Rank_avg  Rank_dense
4      4      Eve     88   28       3.0         2.0
3      3    David     92   30       1.5         1.0
2      2  Charlie     78   22       5.0         4.0
1      1      Bob     92   30       1.5         1.0
0      0    Alice     85   25       4.0         3.0

|Method|	Description|	Duplicate Values	|Gaps in Ranks|	Start Rank|	Best Use Case|
|------|---------|-----------|----------|----------|----------|
average (default)|	Assigns average rank to tied values|	Get average of possible ranks	|Yes|	1	|Statistical analysis
min|	Uses minimum rank for tied group|	All get lowest possible rank	|Yes	|1|	Competitions (best rank)
max|	Uses maximum rank for tied group|	All get highest possible rank	|Yes	|1|	-
first|	Assigns ranks in order of appearance	|Ranked by position in data	|No	|1|	Time series data
dense|	Like 'min' but ranks increase by 1 between groups	|All get lowest possible rank	|No|	1|	Managerial reports

### **`rank()` Parameters:**

|Parameter	|Values	|Description|
|-----------|-------|-----------|
method|	`'average', 'min', 'max', 'first', 'dense'`	|How to handle ties
`ascending=`|	`True/False`	|Rank in ascending/descending order
`na_option=`|	`'keep', 'top', 'bottom'`	|How to treat NaN values
`pct=`|	`True/False`	|Return percentile ranks
`axis=`	|`0` (index), `1` (columns)	|Axis to rank along

### **`sort_values()` Parameters:**
|Parameter	|Values|	Description|
|----------|-------|-------------|
`by=`	|Column `name(s)` or list	|Column(s) to sort by
`ascending=`|	`True/False` or list	|Sort order for each column
`na_position=`|	`'first'`, `'last'`|	Position of NaN values
`key=`|	Function	|Apply function before sorting
`inplace=`|	`True/False`	|Modify original object

### **`sort_index()` Parameters:**
|Parameter|	Values	|Description|
|---------|---------|-----------|
`ascending=`|	`True`/False`	|Sort index in ascending order
`na_position=`|	`'first'`, `'last'`	|Position of `NaN` in index
`level=`	|int/name	|For MultiIndex, which level to sort
`inplace=`	|`True`/`False`	|Modify original object

### **Key Differences**
|Method	|Purpose	|Returns	|Key Parameters|	In-place Option|	Default Behavior|
|------|----------|-----------|----------|---------|-------|
`rank()`|	Assigns numerical ranks to values|	Series with same index	|`method`, `ascending`, `na_option`, `pct`	|No (returns new Series)	|`method='average'`, `ascending=True`
`sort_values()`|	Sorts data by values|	Sorted DataFrame/Series|	`by`, `ascending`, `na_position`, `key`	|`inplace=False` (default)	|`ascending=True`, `na_position='last'`
`sort_index()`|	Sorts data by index	Sorted| DataFrame/Series	|`ascending`, `na_position`, `level`	|`inplace=False` (default)	|`ascending=True`

### Axis Indexes with Duplicate Labels

In [7]:
# Create Series & DataFrame with duplicate index
obj = pd.Series(range(5), index=['a', 'a', 'b', 'b', 'c'])
df = pd.DataFrame(range(5), index=['a', 'a', 'b', 'b', 'c'])
obj.index.is_unique # Falce
# Selecting index 'a' which is duplicate
obj['a'] # Output is Series: because there is a duplicate index
obj['c'] # Output is a scalar

# It's a same in the DataFrame

np.int64(4)

In [8]:
# Example of problematic code
def process_data(label):
    result = obj[label]
    # Problem: result can be Series or scalar
    # This causes errors in subsequent operations
    return result.mean()  # May cause error if result is scalar

# Using list to ensure consistency
result = obj[['a']]  # Even for single value
# Always returns a Series

def safe_process(label):
    result = obj[label]
    if isinstance(result, pd.Series):
        return result.mean()
    else:  # scalar
        return result
    
# For DataFrame
df.loc[['b']]  # Always returns DataFrame even for single row

   0
b  2
b  3

#### Grouping

In [ ]:
# Duplicate indices are automatically grouped
obj.groupby(level=0).sum()

# Various aggregation operations can be performed
obj.groupby(level=0).mean()  # Average
obj.groupby(level=0).first() # First value 
obj.groupby(level=0).last()  # Last value

Key Points
- Many pandas functions require unique indices (like `reindex`, `pivot`)
- Data selection behaves differently depending on duplicate indices
- Recommendation: Use unique indices whenever possible
- If you have duplicate indices: Always consider output type of selection operations
- To remove duplicates: Use `reset_index()` or create multi-level index

In [10]:
# Creating data with duplicate indices (e.g., time data with duplicate seconds)
times = pd.date_range('2023-01-01', periods=6, freq='s')
data = pd.Series([1, 2, 3, 4, 5, 6], index=times)

# Intentionally adding duplicates
dup_times = list(times) + [times[0]]  # Adding first time again
dup_data = pd.Series([1, 2, 3, 4, 5, 6, 7], index=dup_times)

print("Is index unique?", dup_data.index.is_unique)  # False

print("\nData for duplicate time:")
print(dup_data[dup_times[0]])  # Returns two values

Is index unique? False

Data for duplicate time:
2023-01-01    1
2023-01-01    7
dtype: int64

## Summarizing and Computing Descriptive Statistics

In [11]:
# Creating a sample DataFrame with NaN values
df = pd.DataFrame([[1.4, np.nan], [7.1, -4.5],
                   [np.nan, np.nan], [0.75, -1.3]],
                  index=['a', 'b', 'c', 'd'],
                  columns=['one', 'two'])
df

    one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [ ]:
df.sum() # Sum of columns (default axis=0)
df.sum(axis='columns') # Sum of rows (axis=1 or axis='columns')

# Mean with skipna=False (if there id any value of NaN, the result is NaN)
df.mean(axis='columns', skipna=False) 

# Finding index of maximum and minimum values
df.idxmax()
df.idxmin()

# Cumulative sum
df.cumsum()

# Comprehensive descriptive statistics
df.describe()

            one       two
count  3.000000  2.000000
mean   3.083333 -2.900000
std    3.493685  2.262742
min    0.750000 -4.500000
25%    1.075000 -3.700000
50%    1.400000 -2.900000
75%    4.250000 -2.100000
max    7.100000 -1.300000

In [13]:
# Descriptive statistics for non-numeric data
obj = pd.Series(['a', 'a', 'b', 'c'] * 4)
obj.describe()

count     16
unique     3
top        a
freq       8
dtype: object

|Method|	Description|
|------|---------------|	
`count()`|	Number of non-NA values	
`describe()`	|Compute set of summary statistics	
`min()`, `max()`|	Minimum and maximum values	
`argmin()`, `argmax()`|	Index locations of min/max	
`idxmin()`, `idxmax()`|	Index labels of min/max
`quantile(q)`	|Sample quantile (0 to 1)	
`sum()`	|Sum of values	
`mean()`	|Mean of values	
`median()`|	Arithmetic median
`mad()`|	Mean absolute deviation
`prod()`|	Product of all values	
`var()`	|Sample variance
`std()`|	Sample standard deviation	
`skew()`|	Sample skewness
`kurt()`|	Sample kurtosis
`cumsum()`|	Cumulative sum	
`cummin()`, `cummax()`|	Cumulative min/max	min/max 
`cumprod()`|	Cumulative product	
`diff()`|	First arithmetic difference
`pct_change()`|	Percent changes

### Correlation and Covariance

    cov(X,Y) = Σ[(xi - μx)(yi - μy)] / (n-1)
    corr(X,Y) = cov(X,Y) / (σx * σy)

In [ ]:
s1 = pd.Series([1, 2, 3, 4, 5])
s2 = pd.Series([2, 4, 6, 8, 10])

# Calculate correlation
correlation = s1.corr(s2) # Output: 1.0 (perfect correlation)
covariance = s1.cov(s2) # Output: 5.0

In [ ]:
# Create dates
dates = pd.date_range('2020-01-01', periods=100, freq='D')
np.random.seed(42)

# Create synthetic data for 4 stocks
price_data = pd.DataFrame({
    'AAPL': 100 + np.cumsum(np.random.randn(100) * 0.5),
    'GOOG': 200 + np.cumsum(np.random.randn(100) * 0.7),
    'IBM': 150 + np.cumsum(np.random.randn(100) * 0.3),
    'MSFT': 180 + np.cumsum(np.random.randn(100) * 0.6)
}, index=dates)

# Calculate daily returns (percentage changes)
returns = price_data.pct_change()
print("Daily Returns:\n", returns.tail())

In [ ]:
# Full correlation matrix
correlation_matrix = returns.corr()
print("Correlation Matrix:\n", correlation_matrix)

# Important parameters:
# Correlation calculation method
corr_pearson = returns.corr(method='pearson')   # Default
corr_spearman = returns.corr(method='spearman') # Spearman correlation
corr_kendall = returns.corr(method='kendall')   # Kendall correlation

# Minimum number of non-NA observations
corr_min = returns.corr(min_periods=50)  # Minimum 50 shared data points

In [ ]:
# Full covariance matrix
covariance_matrix = returns.cov()
print("Covariance Matrix:\n", covariance_matrix)

# Degrees of freedom parameter
cov_ddof0 = returns.cov(ddof=0)  # Divide by n
cov_ddof1 = returns.cov(ddof=1)  # Divide by n-1 (default)

#### Correlation with another

In [ ]:
# Correlation of each column with a specific Series
ibm_correlations = returns.corrwith(returns['IBM'])
print("Correlations with IBM:\n", ibm_correlations)

# Correlation with another DataFrame
# Assume volume is trading volume data
volume_data = pd.DataFrame({
    'AAPL': np.random.randint(1000000, 5000000, 100),
    'GOOG': np.random.randint(500000, 3000000, 100),
    'IBM': np.random.randint(200000, 1500000, 100),
    'MSFT': np.random.randint(800000, 4000000, 100)
}, index=dates)

price_volume_corr = returns.corrwith(volume_data)
print("Correlation between returns and volume:\n", price_volume_corr)

# Row-wise correlation (axis=1)
returns_transposed = returns.T  # Transpose for example
row_correlations = returns.corrwith(returns_transposed, axis=1)

#### Filtering based on correlation

In [ ]:
# Finding stock pairs with high correlation
corr_matrix = returns.corr()

# Convert matrix to long format
corr_pairs = corr_matrix.stack().reset_index()
corr_pairs.columns = ['Stock1', 'Stock2', 'Correlation']

# Remove self-correlations and duplicates
corr_pairs = corr_pairs[corr_pairs['Stock1'] != corr_pairs['Stock2']]
corr_pairs = corr_pairs.drop_duplicates(subset=['Correlation'])

# Filter strong correlations
strong_corr = corr_pairs[abs(corr_pairs['Correlation']) > 0.7]
print("Strong correlations:\n", strong_corr)

In [ ]:
# day rolling correlation
rolling_corr = returns['AAPL'].rolling(window=20).corr(returns['MSFT'])
print("Rolling correlation of AAPL and MSFT:\n", rolling_corr.tail())

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns

# ایجاد heatmap / Create heatmap
plt.figure(figsize=(10, 8))
sns.heatmap(corr_matrix, 
            annot=True, 
            cmap='coolwarm', 
            center=0,
            square=True,
            linewidths=0.5)
plt.title('Stock Correlation Matrix')
plt.show()

In [ ]:
# Correlation only on days with positive returns
positive_days = returns[returns['AAPL'] > 0]
positive_corr = positive_days[['AAPL', 'MSFT']].corr().iloc[0, 1]
print(f"Correlation on positive days: {positive_corr:.4f}")

# Correlation only on days with negative returns
negative_days = returns[returns['AAPL'] < 0]
negative_corr = negative_days[['AAPL', 'MSFT']].corr().iloc[0, 1]
print(f"Correlation on negative days: {negative_corr:.4f}")

### **`corr():`**
|Parameter	| Possible Values	|Description|
|-----------|-------------------|-----------|
`method=`|	`'pearson', 'spearman', 'kendall`'|	Correlation calculation method
`min_periods=`| Integer	|Minimum number of non-NA observations
`numeric_only=`|	`True`/`False`	|Consider only numeric columns

### **`cov():`**
|Parameter	|Possible Values	|Description|
|-----------|-------------------|-----------|
`ddof`| Integer (usually 0 or 1)	| Degrees of freedom
`min_periods`	| Integer	| Minimum number of non-NA observations
`numeric_only`|	True/False	| Consider only numeric columns

#### Handling NA values

In [ ]:
# NA values are automatically removed
# Can specify minimum number of data points
corr_with_na = returns.corr(min_periods=50)

#### Differences between correlation methods

- Pearson: Linear relationship (default)
- Spearman: Monotonic relationship (non-linear)
- Kendall: Similar to Spearman but for ranked data

#### Performance with large data

In [ ]:
# For very large datasets
corr_fast = returns.corr(method='pearson')  # Fastest

#### Correlation between DataFrames

In [ ]:
# Two DataFrames with similar columns
df1 = pd.DataFrame(np.random.randn(100, 4), columns=['A', 'B', 'C', 'D'])
df2 = pd.DataFrame(np.random.randn(100, 4), columns=['A', 'B', 'C', 'D'])

# Correlation of corresponding columns
cross_corr = df1.corrwith(df2)
print("Correlation between two DataFrames:\n", cross_corr)

| Method | Use Case | Output|
|--------|----------|-------|
`Series.corr(other)`	| Correlation of two Series	| Number
`Series.cov(other)`	|Covariance of two Series	| Number
`DataFrame.corr()`	| Correlation matrix	| DataFrame
`DataFrame.cov()	`| Covariance matrix|	DataFrame
`DataFrame.corrwith(other)` | Correlation with another object	|Series

### Unique Values, Value Counts, and Membership

In [3]:
# Creating a sample Series
obj = pd.Series(['c', 'a', 'd', 'a', 'a', 'b', 'b', 'c', 'c'])

# Extracting unique values from Series
uniques = obj.unique()
print(uniques)

# Sorting unique values if needed
sorted_uniques = np.sort(uniques)
print(sorted_uniques)  # ['a' 'b' 'c' 'd']

# Counting frequency of each value
value_counts = obj.value_counts()
print(value_counts)

['c' 'a' 'd' 'b']
['a' 'b' 'c' 'd']
c    3
a    3
b    2
d    1
Name: count, dtype: int64

In [6]:
# Using value_counts as a top-level function
print(pd.Series(obj).value_counts())

# Getting percentage instead of count
obj.value_counts(normalize=True)

c    3
a    3
b    2
d    1
Name: count, dtype: int64

c    0.333333
a    0.333333
b    0.222222
d    0.111111
Name: proportion, dtype: float64

In [7]:
# Checking membership in a set of values
mask = obj.isin(['b', 'c'])
print(mask)

# Filtering using the boolean mask
filtered = obj[mask]
print(filtered)

# Creating sample Series for matching
to_match = pd.Series(['c', 'a', 'b', 'b', 'c', 'a'])
unique_vals = pd.Series(['c', 'b', 'a'])

# Getting index positions
indices = pd.Index(unique_vals).get_indexer(to_match)
print(indices)

0     True
1    False
2    False
3    False
4    False
5     True
6     True
7     True
8     True
dtype: bool
0    c
5    b
6    b
7    c
8    c
dtype: object
[0 2 1 1 0 2]

|Method|	Description	|
|------|----------------|
`isin()`	|Compute boolean array indicating membership
`match()`|	Compute integer indices for matching
`unique()`|	Compute array of unique values
`value_counts()`|	Return Series with value frequencies

In [11]:
# Creating a sample DataFrame
data = pd.DataFrame({'Qu1': [1, 3, 4, 3, 4],
                     'Qu2': [2, 3, 1, 2, 3],
                     'Qu3': [1, 5, 2, 4, 4]})
print(data)
# Applying value_counts to all columns
result = data.apply(pd.value_counts).fillna(0)
print(result)

   Qu1  Qu2  Qu3
0    1    2    1
1    3    3    5
2    4    1    2
3    3    2    4
4    4    3    4
   Qu1  Qu2  Qu3
1  1.0  1.0  1.0
2  0.0  2.0  1.0
3  2.0  2.0  0.0
4  2.0  0.0  2.0
5  0.0  0.0  1.0

/tmp/ipykernel_1039/1917617667.py:7: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  result = data.apply(pd.value_counts).fillna(0)

In [12]:
# Analyzing categorical survey data
survey_data = pd.DataFrame({
    'Age_Group': ['18-25', '26-35', '18-25', '36-45', '26-35', '18-25'],
    'Satisfaction': ['High', 'Medium', 'High', 'Low', 'Medium', 'High']
})

# Count unique values in each column
for col in survey_data.columns:
    print(f"\nColumn: {col}")
    print(survey_data[col].value_counts())

Column: Age_Group
Age_Group
18-25    3
26-35    2
36-45    1
Name: count, dtype: int64

Column: Satisfaction
Satisfaction
High      3
Medium    2
Low       1
Name: count, dtype: int64

In [13]:
# Filtering based on multiple conditions
products = pd.Series(['Apple', 'Banana', 'Orange', 'Grape', 'Apple', 'Banana'])

# Filter for specific fruits
favorite_fruits = ['Apple', 'Orange']
filtered_products = products[products.isin(favorite_fruits)]
print(filtered_products)

0     Apple
2    Orange
4     Apple
dtype: object

In [14]:
# Calculating percentage frequency
grades = pd.Series(['A', 'B', 'A', 'C', 'B', 'A', 'B', 'B', 'C'])
grade_percentages = grades.value_counts(normalize=True) * 100
print("Grade percentages:")
print(grade_percentages)

Grade percentages:
B    44.444444
A    33.333333
C    22.222222
Name: proportion, dtype: float64