# Data Cleaning and Preparation.

## Missing Data

In [1]:
import pandas as pd
import numpy as np

In [2]:
# Creating a pandas Series with some missing data
string_data = pd.Series(['aardvark', 'artichoke', np.nan, 'avocado'])

# Assign None to first element
string_data[0] = None

# Check which values are missing
print(string_data.isnull())
print(string_data.isnull().sum)

0     True
1    False
2     True
3    False
dtype: bool
<bound method Series.sum of 0     True
1    False
2     True
3    False
dtype: bool>

In [3]:
# Import NaN as NA for shorter code
from numpy import nan as NA
data = pd.Series([1, NA, 3.5, NA, 7])

# Drop all missing values
print(data.dropna())

# Alternative way using boolean indexing
data[data.notnull()]

0    1.0
2    3.5
4    7.0
dtype: float64

0    1.0
2    3.5
4    7.0
dtype: float64

In [ ]:
data = pd.DataFrame([[1., 6.5, 3.], [1., NA, NA],
                     [NA, NA, NA], [NA, 6.5, 3.]])

# Only drop rows where ALL values are NA
data.dropna(how='all')

     0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
3  NaN  6.5  3.0

In [5]:
# Create a DataFrame with random numbers
df = pd.DataFrame(np.random.randn(7, 3))

# In[28]: Set some values to NA
df.iloc[:4, 1] = NA 
df.iloc[:2, 2] = NA 

# View the DataFrame
df

          0         1         2
0  0.879568       NaN       NaN
1 -0.297959       NaN       NaN
2  0.906999       NaN -0.671219
3  0.697578       NaN -0.832349
4 -1.965084  0.470033 -0.700002
5 -1.161618  1.084250  1.359708
6  1.284482 -0.625999 -0.112195

In [6]:
# Fill all NaN with 5
df.fillna(5)

          0         1         2
0  0.879568  5.000000  5.000000
1 -0.297959  5.000000  5.000000
2  0.906999  5.000000 -0.671219
3  0.697578  5.000000 -0.832349
4 -1.965084  0.470033 -0.700002
5 -1.161618  1.084250  1.359708
6  1.284482 -0.625999 -0.112195

In [7]:
# Filll each column with different values
df.fillna({1: 0.5, 2: 0})

          0         1         2
0  0.879568  0.500000  0.000000
1 -0.297959  0.500000  0.000000
2  0.906999  0.500000 -0.671219
3  0.697578  0.500000 -0.832349
4 -1.965084  0.470033 -0.700002
5 -1.161618  1.084250  1.359708
6  1.284482 -0.625999 -0.112195

In [8]:
# Forward fill - propagate last valid value forward
df.ffill()

          0         1         2
0  0.879568       NaN       NaN
1 -0.297959       NaN       NaN
2  0.906999       NaN -0.671219
3  0.697578       NaN -0.832349
4 -1.965084  0.470033 -0.700002
5 -1.161618  1.084250  1.359708
6  1.284482 -0.625999 -0.112195

In [9]:
# Example of backward fill - propagate next valid value backward
df.bfill()

          0         1         2
0  0.879568  0.470033 -0.671219
1 -0.297959  0.470033 -0.671219
2  0.906999  0.470033 -0.671219
3  0.697578  0.470033 -0.832349
4 -1.965084  0.470033 -0.700002
5 -1.161618  1.084250  1.359708
6  1.284482 -0.625999 -0.112195

In [10]:
# Fill missing values with the mean of the Series
data.fillna(data.mean())

     0    1    2
0  1.0  6.5  3.0
1  1.0  6.5  3.0
2  1.0  6.5  3.0
3  1.0  6.5  3.0

In [11]:
# Example: Fill with median instead of mean
data.fillna(data.median())

     0    1    2
0  1.0  6.5  3.0
1  1.0  6.5  3.0
2  1.0  6.5  3.0
3  1.0  6.5  3.0

In [12]:
# Keep rows with at least 2 non-NA values
df.dropna(thresh=2)

          0         1         2
2  0.906999       NaN -0.671219
3  0.697578       NaN -0.832349
4 -1.965084  0.470033 -0.700002
5 -1.161618  1.084250  1.359708
6  1.284482 -0.625999 -0.112195

In [13]:
# Advanced Example: Different strategies for different columns
df_advanced = pd.DataFrame({
    'A': [1, np.nan, 3, np.nan, 5],
    'B': [10, 20, np.nan, 40, np.nan],
    'C': ['x', 'y', np.nan, 'z', np.nan]
})

# Fill numeric columns with mean, categorical with mode
fill_values = {
    'A': df_advanced['A'].mean(),     
    'B': df_advanced['B'].median(),  
    'C': df_advanced['C'].mode()[0] 
}

df_advanced_filled = df_advanced.fillna(fill_values)
df_advanced_filled

     A     B  C
0  1.0  10.0  x
1  3.0  20.0  y
2  3.0  20.0  x
3  3.0  40.0  z
4  5.0  20.0  x

### **Dropping Missing Values - dropna()**
|Parameter|	Description	|Default|
|---------|-------------|-------|
`axis`	|Drop rows (0) or columns (1)	| `0`
`how`	|`'any'` (drop if any NaN) or 'all' (drop if all NaN)	|`'any'`
`thresh`|	Require at least N non-NA values to keep	| `None`
`subset`|	Columns to consider for NaN detection|	`None`
`inplace`|	Modify the original DataFrame	| `False

### **Filling Missing Values - fillna()**
| Parameter|	Description|	Default|
|----------|---------------|-----------|
`value`|	Scalar value or dict to fill NaN's	|Required
`method`|	`'ffill'` (forward fill) or` 'bfill'` (backward fill)	|`None`
`axis`	|Axis to fill on|	`0`
`inplace`	|Modify without copy	|`False`
`limit`	|Max consecutive periods to fill	|`None`

### **Quick Reference Card**
|Task	|Code|
|-------|----|
Remove all rows with any NaN	|`df.dropna()`
Remove columns with any NaN	|`df.dropna(axis=1)`
Fill all NaN with a fixed value	|`df.fillna(0)`
Forward fill	|`df.ffill()` or `df.fillna(method='ffill')`
Backward fill|`	df.bfill()` or `df.fillna(method='bfill')`
Fill with column mean	|`df.fillna(df.mean())`
Check if any NaN exists	|`df.isnull().any().any()`
Count NaN per column	|`df.isnull().sum()`
Keep rows with at least N non-NA	|`df.dropna(thresh=N)`

    Note: Methods with inplace=True modify the original DataFrame. Use with caution or create a copy first with df.copy().

## Data Transformation

In [14]:
# Create a DataFrame with duplicate rows
data = pd.DataFrame({'k1': ['one', 'two'] * 3 + ['two'],
                     'k2': [1, 1, 2, 3, 3, 4, 4]})

# Check for duplicate rows (returns boolean Series)
print(data.duplicated())

# Remove duplicate rows, keep first occurrence
print(data.drop_duplicates())

0    False
1    False
2    False
3    False
4    False
5    False
6     True
dtype: bool
    k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4

In [ ]:
# Add a new column for demonstration
data['v1'] = range(7)
print(data)

# Remove duplicates based only on 'k1' column
data.drop_duplicates(['k1'])

    k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
5  two   4   5
6  two   4   6

    k1  k2  v1
0  one   1   0
1  two   1   1

In [16]:
# Keep last occurrence of duplicates
data.drop_duplicates(['k1', 'k2'], keep='last')

    k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
6  two   4   6

In [60]:
# Create a DataFrame with meat types
data = pd.DataFrame({
    'food': ['bacon', 'pulled pork', 'bacon', 'Pastrami', 'corned beef', 
             'Bacon', 'pastrami', 'honey ham', 'nova lox'],
    'ounces': [4, 3, 12, 6, 7.5, 8, 3, 5, 6]
})

# Define a mapping from meat to animal
meat_to_animal = {
    'bacon': 'pig',
    'pulled pork': 'pig',
    'pastrami': 'cow',
    'corned beef': 'cow',
    'honey ham': 'pig',
    'nova lox': 'salmon'
}

# Convert all food names to lowercase
lowercased = data['food'].str.lower()

# Map food names to animal names using the dictionary
data['animal'] = lowercased.map(meat_to_animal)
data

          food  ounces  animal
0        bacon     4.0     pig
1  pulled pork     3.0     pig
2        bacon    12.0     pig
3     Pastrami     6.0     cow
4  corned beef     7.5     cow
5        Bacon     8.0     pig
6     pastrami     3.0     cow
7    honey ham     5.0     pig
8     nova lox     6.0  salmon

In [18]:
# Use lambda function to combine lowercase conversion and mapping in one step
data['food'].map(lambda x: meat_to_animal[x.lower()])

0       pig
1       pig
2       pig
3       cow
4       cow
5       pig
6       cow
7       pig
8    salmon
Name: food, dtype: object


#### **Working with Duplicate Records**
`duplicated()` - Detect duplicate rows
- Returns Boolean Series (True for duplicates)
- By default, marks all duplicates except the first occurrence

|Parameter|	Description|	Default|
|---------|------------|-----------|
`subset`|	Columns to consider for duplicate detection	|All columns
`keep`	|Which occurrence to keep: `'first'`, `'last'`, or False (remove all)	| '`first`'
`inplace`	|Modify the original DataFrame	| Fa`lse
`ignore_index`	|Reset index after dropping	| `False`

#### **Comparison: `map()` vs `apply()` vs `replace()`**
|Method	|Use Case	|Example|
|-------|-----------|-------|
`Series.map()`	|Element-wise mapping (Series only)	|`s.map({'A': 1})`
`Series.apply()`	|Element-wise with function|	`s.apply(lambda x: func(x))`
`DataFrame.apply()`	|Apply function to rows/columns|`	df.apply(func, axis=1)`
`DataFrame.replace()`	|Replace values in entire DataFrame|	`df.replace({'old': 'new'})`

#### Pro Tips:

    Use duplicated() first to inspect before dropping
    Always check the impact of keep=False (removes all duplicates)
    Use str.lower() before mapping to ensure case-insensitive matching
    Lambda functions are great for quick transformations but use named functions for complex logic

### Replacing Values

In [19]:
# Create a Series with sentinel values (markers for missing data)
data = pd.Series([1., -999., 2., -999., -1000., 3.])

# Create a new Series unless use inplace=True
data.replace([-999, -1000], np.nan)

0    1.0
1    NaN
2    2.0
3    NaN
4    NaN
5    3.0
dtype: float64

In [20]:
# Replace each value with a different replacement using lists
data.replace([-999, -1000], [np.nan, 0])

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [21]:
# Replace values using a dictionary (key = old value, value = new value)
data.replace({-999: np.nan, -1000: 0})

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [ ]:
# Create a DataFrame with custom index and columns
data = pd.DataFrame(np.arange(12).reshape((3, 4)),
                    index=['Ohio', 'Colorado', 'New York'],
                    columns=['one', 'two', 'three', 'four'])
print(data)

# Define lambda to take first 4 characters and uppercase them
transform = lambda x: x[:4].upper()

# Apply transformation to index using map
data.index.map(transform)

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
New York    8    9     10    11

Index(['OHIO', 'COLO', 'NEW '], dtype='object')

In [23]:
# Assign transformed index to the DataFrame (in-place modification)
data_index= data.index = data.index.map(transform)
print(data_index)

Index(['OHIO', 'COLO', 'NEW '], dtype='object')

In [24]:
# Use rename to create a new DataFrame with transformed labels
print(data.rename(index=str.title, columns=str.upper))

      ONE  TWO  THREE  FOUR
Ohio    0    1      2     3
Colo    4    5      6     7
New     8    9     10    11

In [25]:
# Use rename with dictionary to change specific index and column labels
data_rename = data.rename(index={'OHIO': 'INDIANA'},
            columns={'three': 'peekaboo'})
print(data_rename)

# Modify the DataFrame in-place (no new object created)
data.rename(index={'OHIO': 'INDIANA'}, inplace=True)
print(data)

         one  two  peekaboo  four
INDIANA    0    1         2     3
COLO       4    5         6     7
NEW        8    9        10    11
         one  two  three  four
INDIANA    0    1      2     3
COLO       4    5      6     7
NEW        8    9     10    11

### Discretization and Binning

In [26]:
# Age data of individuals
ages = [20, 22, 25, 27, 21, 23, 37, 31, 61, 45, 41, 32]

# Define bin edges (boundaries of each group)
bins = [18, 25, 35, 60, 100]

# Discretize ages into these bins
pd.cut(ages, bins) # right=Falce : [18, 25]

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64, right]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [27]:
group_names = ['Youth', 'YoungAdult', 'MiddleAged', 'Senior']
pd.cut(ages, bins, labels=group_names)

['Youth', 'Youth', 'Youth', 'YoungAdult', 'Youth', ..., 'YoungAdult', 'Senior', 'MiddleAged', 'MiddleAged', 'YoungAdult']
Length: 12
Categories (4, object): ['Youth' < 'YoungAdult' < 'MiddleAged' < 'Senior']

In [28]:
# Split into 4 equal-width bins (2 decimal precision)
data = np.random.rand(20)
pd.cut(data, 4, precision=2)

[(0.61, 0.81], (0.42, 0.61], (0.026, 0.22], (0.22, 0.42], (0.42, 0.61], ..., (0.22, 0.42], (0.22, 0.42], (0.22, 0.42], (0.026, 0.22], (0.22, 0.42]]
Length: 20
Categories (4, interval[float64, right]): [(0.026, 0.22] < (0.22, 0.42] < (0.42, 0.61] < (0.61, 0.81]]

In [29]:
data = np.random.randn(1000)

# Split into 4 quartiles
cats = pd.qcut(data, 4)

# Value counts (each should have ~250)
pd.Series(cats).value_counts()

(-3.23, -0.664]      250
(-0.664, -0.0397]    250
(-0.0397, 0.652]     250
(0.652, 2.975]       250
Name: count, dtype: int64

In [30]:
# Custom percentiles: 0th, 10th, 50th, 90th, 100th
pd.qcut(data, [0, 0.1, 0.5, 0.9, 1.])

[(-0.0397, 1.271], (-0.0397, 1.271], (-0.0397, 1.271], (-0.0397, 1.271], (-1.276, -0.0397], ..., (-0.0397, 1.271], (-3.23, -1.276], (-0.0397, 1.271], (-1.276, -0.0397], (-1.276, -0.0397]]
Length: 1000
Categories (4, interval[float64, right]): [(-3.23, -1.276] < (-1.276, -0.0397] < (-0.0397, 1.271] < (1.271, 2.975]]

### Detecting and Filtering Outliers

In [62]:
data = pd.DataFrame(np.random.randn(1000, 4))
data.describe()

                 0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean      0.025619    -0.002790    -0.069612     0.065019
std       1.006798     0.996797     0.996400     0.991650
min      -3.184377    -3.745356    -3.428254    -3.548824
25%      -0.641675    -0.644144    -0.774890    -0.596286
50%       0.002073    -0.014664    -0.117489     0.094503
75%       0.680391     0.654328     0.611729     0.777558
max       3.260383     3.927528     3.366626     2.653656

In [63]:
col = data[2]
col[np.abs(col) > 3]

520   -3.428254
897    3.366626
Name: 2, dtype: float64

In [ ]:
# any(1) checks if at least one True exists per row

mask = (np.abs(data) > 3)
data[mask.any(axis=1)]

            0         1         2         3
3    3.248944 -1.021228 -0.577087  0.124121
95   0.106061  3.927528 -0.255126  0.854137
100  3.176873  0.959533 -0.975340 -1.116742
303 -0.025907 -3.399312 -0.974657 -0.685312
322  3.260383  0.963301  1.201206 -1.852001
398 -0.196713 -3.745356 -1.520113 -0.346839
497 -3.056990  1.918403 -0.578828  1.847446
520  0.326045  0.425384 -3.428254 -0.296336
584 -3.184377  1.369891 -1.074833 -0.089937
805  0.208011 -0.150923 -0.362528 -3.548824
897  0.193299  1.397822  3.366626 -2.372214

In [33]:
# Replace >3 with 3 and <-3 with -3
data[np.abs(data) > 3] = np.sign(data) * 3

### Permutation and Random Sampling

In [34]:
df = pd.DataFrame(np.arange(5 * 4).reshape((5, 4)))

# Random new order for indices
sampler = np.random.permutation(5)

# Reorder DataFrame based on new order
df.take(sampler)   # or df.iloc[sampler]

    0   1   2   3
2   8   9  10  11
1   4   5   6   7
0   0   1   2   3
4  16  17  18  19
3  12  13  14  15

In [35]:
# Pick 3 random rows (no duplicates)
df.sample(n=3)

    0   1   2   3
2   8   9  10  11
4  16  17  18  19
1   4   5   6   7

In [36]:
# Sample 10 times with replacement
choices = pd.Series([5, 7, -1, 6, 4])
choices.sample(n=10, replace=True)

0    5
2   -1
2   -1
3    6
1    7
4    4
1    7
1    7
2   -1
3    6
dtype: int64

### Dummy Variables

In [ ]:
df = pd.DataFrame({
    'key': ['b', 'b', 'a', 'c', 'a', 'b'],
    'data1': range(6)   # 0,1,2,3,4,5
})

# Create dummy variables for column 'key'
pd.get_dummies(df['key'])

       a      b      c
0  False   True  False
1  False   True  False
2   True  False  False
3  False  False   True
4   True  False  False
5  False   True  False

In [38]:
# Dummy columns with prefix 'key_'
pd.get_dummies(df['key'], prefix='key')

   key_a  key_b  key_c
0  False   True  False
1  False   True  False
2   True  False  False
3  False  False   True
4   True  False  False
5  False   True  False

In [ ]:
# English: Read movies file with '::' separator
mnames = ['movie_id', 'title', 'genres']
movies = pd.read_csv('data/movie.csv', header=None, names=mnames)
movies

,movie_id,title,genres
0,1,Toy Story (1995),Animation|Children's|Comedy
1,2,Jumanji (1995),Adventure|Children's|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama
4,5,Father of the Bride Part II (1995),Comedy
5,6,Heat (1995),Action|Crime|Thriller
6,7,Sabrina (1995),Comedy|Romance
7,8,Tom and Huck (1995),Adventure|Children's
8,9,Sudden Death (1995),Action
9,10,GoldenEye (1995),Action|Adventure|Thriller

In [40]:
# Extract list to collect all genres
all_genres = []
for x in movies.genres:
    all_genres.extend(x.split('|'))

genres = np.unique(all_genres)
genres

array([' Action', ' Adventure', ' Comedy', 'Adventure', 'Animation',
       "Children's", 'Comedy', 'Crime', 'Drama', 'Fantasy', 'Romance',
       'Thriller'], dtype='<U10')

In [ ]:
# Zero matrix with rows = number of movies, columns = number of genres
zero_matrix = np.zeros((len(movies), len(genres)))

# Convert to DataFrame with column names = genre names
dummies = pd.DataFrame(zero_matrix, columns=genres)
dummies

,Action,Adventure,Comedy,Adventure,Animation,Children's,Comedy,Crime,Drama,Fantasy,Romance,Thriller
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [42]:
# Iterate over all movies with row index
for i, gen in enumerate(movies.genres):
    # Find column positions of each genre in genres list
    indices = dummies.columns.get_indexer(gen.split('|'))
    
    # Set 1 in those columns for row i
    dummies.iloc[i, indices] = 1
dummies

,Action,Adventure,Comedy,Adventure,Animation,Children's,Comedy,Crime,Drama,Fantasy,Romance,Thriller
0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0
1,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
2,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
4,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
6,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
7,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
8,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [43]:
# Generate 10 reproducible random numbers
np.random.seed(12345)
values = np.random.rand(10)

# Define bins from 0 to 1 (width 0.2)
bins = [0, 0.2, 0.4, 0.6, 0.8, 1]

# First cut (binning) then get_dummies (one-hot)
pd.get_dummies(pd.cut(values, bins))

   (0.0, 0.2]  (0.2, 0.4]  (0.4, 0.6]  (0.6, 0.8]  (0.8, 1.0]
0       False       False       False       False        True
1       False        True       False       False       False
2        True       False       False       False       False
3       False        True       False       False       False
4       False       False        True       False       False
5       False       False        True       False       False
6       False       False       False       False        True
7       False       False       False        True       False
8       False       False       False        True       False
9       False       False       False        True       False

## String Manipulation

In [ ]:
val = 'a,b, guido'
val.split(',')

In [ ]:
# Combine split and strip with list comprehension
pieces = [x.strip() for x in val.split(',')]

In [66]:
pieces = 'first', 'second', 'third'
'::'.join(pieces)

'first::second::third'

In [67]:
val.replace(',', '::')

'a::b:: guido'

| Method | Description | Syntax Example | Example Output |
|--------|-------------|----------------|----------------|
| `count(sub)` | Return number of non-overlapping occurrences of sub | `"hello hello".count("hello")` | `2` |
| `endswith(suffix)` | Return `True` if string ends with suffix | `"hello.py".endswith(".py")` | `True` |
| `startswith(prefix)` | Return `True` if string starts with prefix | `"hello.py".startswith("hell")` | `True` |
| `join(iterable)` | Use string as delimiter to concatenate sequence of strings | `"-".join(["a", "b", "c"])` | `"a-b-c"` |
| `index(sub)` | Return position of first char of sub; raise `ValueError` if not found | `"hello".index("e")` | `1` |
| `find(sub)` | Like `index` but return `-1` if not found | `"hello".find("x")` | `-1` |
| `rfind(sub)` | Return position of last occurrence of sub; return `-1` if not found | `"hello hello".rfind("hello")` | `6` |
| `replace(old, new)` | Replace occurrences of `old` with `new` | `"hello".replace("l", "x")` | `"hexxo"` |
| `strip()` | Trim whitespace (including newlines) from both ends | `"  hi\n".strip()` | `"hi"` |
| `rstrip()` | Trim whitespace from right end | `"hi  ".rstrip()` | `"hi"` |
| `lstrip()` | Trim whitespace from left end | `"  hi".lstrip()` | `"hi"` |
| `split(delim)` | Break string into list of substrings using `delim` | `"a,b,c".split(",")` | `["a", "b", "c"]` |
| `lower()` | Convert all alphabet characters to lowercase | `"HeLLo".lower()` | `"hello"` |
| `upper()` | Convert all alphabet characters to uppercase | `"HeLLo".upper()` | `"HELLO"` |
| `casefold()` | Aggressive lowercase for case‑insensitive matching (e.g., `ß` → `ss`) | `"Straße".casefold()` | `"strasse"` |
| `ljust(width)` | Left justify, pad right with spaces to reach `width` | `"hi".ljust(4)` | `"hi  "` |
| `rjust(width)` | Right justify, pad left with spaces to reach `width` | `"hi".rjust(4)` | `"  hi"` |

### Regex

In [46]:
import re

In [ ]:
# Text with spaces, tabs, and multiple whitespace characters
text = "foo bar\t baz \tqux"

# Pattern: one or more whitespace characters (space, tab, newline)
re.split(r'\s+', text)

['foo', 'bar', 'baz', 'qux']

In [ ]:
# Compile pattern for reuse
regex = re.compile(r'\s+')

# Now we can use it multiple times
regex.split(text)

[' ', '\t ', ' \t']

In [68]:
regex.findall(text)

[('dave', 'google', 'com'),
 ('steve', 'gmail', 'com'),
 ('rob', 'gmail', 'com'),
 ('ryan', 'yahoo', 'com')]

In [69]:
# Correct way - use r before the string
re.compile(r'\s+')

re.compile(r'\s+', re.UNICODE)

In [70]:
# Incorrect way (needs double backslash)
re.compile('\\s+')

re.compile(r'\s+', re.UNICODE)

In [50]:
# A multiline text with emails
text = """Dave dave@google.com
Steve steve@gmail.com
Rob rob@gmail.com
Ryan ryan@yahoo.com
"""

# Email pattern (simplified)
pattern = r'[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}'
regex = re.compile(pattern, flags=re.IGNORECASE)

# Find all emails (list of strings)
regex.findall(text)

['dave@google.com', 'steve@gmail.com', 'rob@gmail.com', 'ryan@yahoo.com']

In [51]:
# Search for the first email (returns a match object)
regex.search(text)

In [53]:
# match only works if pattern starts at the very beginning
print(regex.match(text))

None

In [72]:
# Grouping: (username)@(domain).(suffix)
pattern = r'([A-Z0-9._%+-]+)@([A-Z0-9.-]+)\.([A-Z]{2,4})'
regex = re.compile(pattern, flags=re.IGNORECASE)

email = regex.match('wesm@bright.net')
email.groups()   # ('wesm', 'bright', 'net')

('wesm', 'bright', 'net')

In [ ]:
# See start and end position in original text
email.start()

0

In [ ]:
email.end()

15

In [ ]:
text[email.start():email.end()]

'Dave dave@googl'

In [56]:
# findall with groups returns a list of tuples
regex.findall(text)

[('dave', 'google', 'com'),
 ('steve', 'gmail', 'com'),
 ('rob', 'gmail', 'com'),
 ('ryan', 'yahoo', 'com')]

In [57]:
print(regex.sub(r'Username: \1, Domain: \2, Suffix: \3', text))

Dave Username: dave, Domain: google, Suffix: com
Steve Username: steve, Domain: gmail, Suffix: com
Rob Username: rob, Domain: gmail, Suffix: com
Ryan Username: ryan, Domain: yahoo, Suffix: com